anticollect_org/apps/blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='BlogList'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='BlogDetail')
]

anticollect_org/apps/bot/urls.py
from django.urls import path
from .tbb import sbot


urlpatterns = [
    path('D@NetQ3kNMh&4c-eRNw=_wVkfqM$j^Cd+b+BP9uyHsNG-Gaj*8+NBL_3qyEkzFWT/', sbot, name="bot"),
]

anticollect_org/apps/clients/urls.py
from django.urls import path
from .views import ClientsView

app_name = 'clients'

urlpatterns =[
    path('', ClientsView.as_view(), name='clients')
]

anticollect_org/apps/index/urls.py
from django.urls import path
# from . import views
from .views import index# BlocksListView

app_name = 'index'

urlpatterns = [
    # path('', BlocksListView.as_view(), name='index_page'),
    path('', index, name='index_page'),
]

anticollect_org/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('botTelegram/', include('bot.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('index.urls'), name='main'),
    path('blog/', include('blog.urls'), name='blog'),
    path('clients/', include('clients.urls')),
    path('thanks/', TemplateView.as_view(template_name='thanks.html'), name='thanks')
)

anticollect_org/apps/blog/models.py
from django.db import models
from tinymce.models import HTMLField
from django.urls import reverse
from io import BytesIO
from PIL import Image
from django.core.files import File
from django.utils.safestring import  mark_safe


#take name from path
def ImgName(img):
    arr = img.split('/')
    return arr[-1]

#image compression method
def compress(image):

    im = Image.open(image)
    # imR = im.resize(1600)
    # im_io = BytesIO()
    NewImageName = ImgName(image.name)
    # im_io.name = NewImageName
    im.save(NewImageName, 'JPEG', quality=60, )
    new_image = File(NewImageName, name=NewImageName)
    print('newImage', NewImageName)
    return new_image

def dublicateDelite(image):
    arr = image.split('/')
    arr2 = []
    for a in arr:
        if (arr2.count(a) == 0):
            arr2.append(a)
    newUrls = '/'.join(arr2)
    return newUrls

def newPath(imgPath, image):
    containPath = image.find(imgPath)
    if (containPath >0):
        return dublicateDelite(image)
    else:
        return imgPath + image

# def bannerImg(obj, image):
#     # imgPath = 'photo/' + str(obj.slug) + '/banner.jpeg'
#     # nPath = dublicateDelite(image)
#     return 'photo/' + str(obj.slug) + '/banner.jpeg'

def bannerImg(obj, image):
    imgPath = 'photo/' + str(obj.slug) + '/'
    # dublicateDelite(image)
    return newPath(imgPath, image)

class Blog(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Отключено'),
        ('published', 'Включено'),
    )
    blockName = models.CharField('Краткий Заголовок', max_length=60, help_text='Завликающий краткий заголовок')
    LongBlockName = models.CharField('Полный Заголовок статьи', max_length=150, blank=True, null=True, help_text='Полный заголовок описывающий всю суть')
    slug = models.SlugField('название для url', blank=True, null=True, help_text='название для ссылки, должно быть из латинских букв и цифр')
    created = models.DateTimeField(auto_now_add=True)
    lastmod = models.DateTimeField(auto_now=True)
    idsort = models.PositiveSmallIntegerField(verbose_name='Порядок сортировки', default=1, blank=True, null=True)
    banner = models.ImageField('Баннер для статьи', upload_to=bannerImg, blank=True, null=True, max_length=500,
                               help_text='Добавить привлекательную картинку для статьи')
    text = HTMLField('Наполнение блока', blank=True, max_length=20000)
    status = models.CharField('Состояние', max_length=20, choices=STATUS_CHOICES, null=True, blank=True, default='draft')
    metaDescrioption = models.CharField('SEO описание', max_length=155, null=True, blank=True,
                                        help_text='Описание страницы для поисковиков\n будет видно в снипете(выдача поиска в Google)')
    metaKeyWords = models.CharField('SEO Ключевые слова', max_length=155, null=True, blank=True,
                                    help_text='ключевые слова с поисковиков по теме')

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="150" />' % (self.banner))
    image_tag.short_description = 'Баннер'

    def get_absolute_url(self):
        return reverse('blog:BlogDetail', kwargs={'slug': self.slug, })

    # def save(self, *args, **kwargs):
    #     try:
    #         new_image = compress(self.banner)
    #         # new_image = newPath(imgPath ,compressedImg)
    #         self.banner = new_image
    #     except ValueError:
    #         pass
    #     super().save(*args, **kwargs)

    class Meta:
        ordering = ['id']
        verbose_name = 'Статьи'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.blockName

anticollect_org/apps/clients/models.py
from django.db import models
from django.utils.translation import gettext as _
from index.models import Price
from django.contrib.auth.models import User

class Penalty(models.Model):
    penalty = models.CharField('Завание удержания', max_length=50, null=True, blank=True)
    idsort = models.PositiveSmallIntegerField(verbose_name='Порядок сортировки', default=1)

    class Meta:
        ordering = ['idsort']
        verbose_name = 'Взыскания'
        verbose_name_plural = 'Типы взысканий'

    def __str__(self):
        return self.penalty

class Region(models.Model):
    region = models.CharField('Регион', max_length=50, null=True, blank=True)
    idsort = models.PositiveSmallIntegerField(verbose_name='Порядок сортировки', default=1)

    class Meta:
        ordering = ['idsort']
        verbose_name = 'Регион'
        verbose_name_plural = 'Регионы'

    def __str__(self):
        return self.region

CHOISES_FROM= (
        ('site', 'Сайт'),
        ('viber', 'Viber'),
    )


def cur_user(request):
    loginNow = request.user
    return loginNow


class Clients(models.Model):
    CHOISES_PROCES=(
        ('no_worked', 'Новый Клиент'),
        ('payed', 'Оплачено'),
        ('in_court', 'Подано в Суд'),
        ('to_back', 'Возврат'),
    )
    CHOISES_ZAYAVKA=(
        ('new', 'Новая заявка'),
        ('later', 'Перзвонить Позже'),
        ('dogovor', 'Аванс'),
        ('refusal', 'Отказ'),
    )
    name = models.CharField(_('ПІБ'), max_length=300, null=True, blank=True)
    # tel = PhoneField(help_text='Контактний телефон', E164_only=False)
    tel = models.CharField('Телефон', max_length=20, help_text='Контактний телефон')
    summ = models.FloatField('Стягнута сума, грн *', null=True, blank=True)
    region = models.ForeignKey(Region, verbose_name='Регион', on_delete=models.CASCADE, null=True, blank=True, default='')
    penalty = models.ForeignKey(Penalty, verbose_name='Взыскание',  on_delete=models.CASCADE, null=True, blank=True, default='')
    price = models.ForeignKey(Price, verbose_name='Тариф', on_delete=models.CASCADE, null=True, blank=True, default='')
    about = models.TextField('Описание', null=True, blank=True)
    dateAdd = models.DateTimeField('Дата создания', auto_now_add=True, help_text='Клиент создан', null=True, blank=True)
    lastModificate = models.DateTimeField('Последняя модификация', auto_now=True, help_text='последнее редактирование', null=True)
    processed = models.CharField('Статус клиента', choices=CHOISES_PROCES, max_length=20, blank=True, null=True, default='no_worked')
    pathFrom = models.CharField('Источник', choices=CHOISES_FROM, max_length=10, default='viber')
    datePayment = models.DateField('Дата по дог.', null=True, blank=True, auto_now=False)
    Payment = models.PositiveSmallIntegerField('Cумма по дог.', null=True, blank=True)
    operator = models.ForeignKey(User, verbose_name='Оператор', limit_choices_to={'groups__name': 'Operators'},
                                  null=True, blank=True, on_delete=models.SET_NULL)
    comments = models.TextField('Комментарии юриста', null=True, blank=True)
    manager = models.CharField('Статус заявки', choices=CHOISES_ZAYAVKA, max_length=15, blank=True, null=True, default='new')
    PrePayment = models.PositiveSmallIntegerField('Предоплата', null=True, blank=True)
    manager_comment = models.TextField('Комментарии менеджера', null=True, blank=True)



    class Meta:
        verbose_name = 'Заявка от клиента'
        verbose_name_plural = 'Заявки от клиентов'

    def __str__(self):
        return f'{self.tel}'

anticollect_org/apps/clients/forms.py
from django.core import validators
from django.core.validators import validate_email
from django import forms
from django.utils.translation import gettext_lazy as _
from clients.models import Clients, CHOISES_FROM
from index.models import Price


class ClientsForm(forms.ModelForm):
    price = forms.ModelChoiceField(queryset=Price.objects.all(),
                                   label='', required=False,
                                   empty_label=_("Виберіть послугу"),
                                   widget=forms.Select(attrs={'class': 'form-control'}),
                                   )
    pathFrom = 'site'
    operator = None
    class Meta:
        model = Clients
        fields = ('name', 'tel', 'summ', 'price', 'about', )
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': _('ПІБ'), 'class': 'form-control'}),
            'tel': forms.TextInput(attrs={'placeholder': _('Телефон'), 'class': 'form-control'}),
            'summ': forms.NumberInput(attrs={'placeholder': _('Стягнута сума, грн *'), 'class': 'form-control'}),
            'region': forms.Select(attrs={'class': 'form-control'}),
            'penalty': forms.Select(attrs={'class': 'form-control'}),
            'about': forms.Textarea(attrs={'placeholder': _('Короткий опис ситуації'), 'class': 'form-control'}),
            # 'pathFrom': forms.Textarea(),
        }
        labels = {
            'name': '',
            'email': '',
            'tel': '',
            'comments': '',
            # 'region':_('выберет регион'),
        }
        # default_validators = [
        #     validators.validate_email
        # ]

anticollect_org/apps/blog/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Blog
from index.models import Contacts

class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'
    slug_field = 'slug'
    ordering = 'idsort'
    context_object_name = 'blog_all'
    paginate_by = 12
    queryset = Blog.objects.filter(status='published').order_by('idsort')

    # def get_context_data(self, **kwargs):
    #     context = super(BlogListView, self).get_context_data(**kwargs)
    #     # context['index_all'] = Blocks.objects.filter(status='published').order_by('idsort')
    #     # context['contacts'] = Contacts.objects.get(id=1)
    #     return context

class BlogDetailView(DetailView):
    model = Blog
    context_object_name = 'blog_one'
    # def get_context_data(self, **kwargs):
    #     context = super(BlogDetailView, self).get_context_data(**kwargs)
    #     context['index_all'] = Blocks.objects.filter(status='published').order_by('idsort')
    #     context['contacts'] = Contacts.objects.get(id=1)
    #     return context

anticollect_org/apps/clients/views.py
from django.views.generic import CreateView
from .models import Clients
from bot.tbb import new_clients
from .forms import ClientsForm
from django.contrib.auth.models import User


#from django.core.mail import send_mail


def operator_sort():
    previus = []
    cols = User.objects.filter(groups__name='Operators').count()
    serched = cols - 1
    for i in range(serched):
        previus.append(str(Clients.objects.filter(pathFrom='site').order_by('-dateAdd')[i].operator))
    thisOperator = User.objects.filter(groups__name='Operators').exclude(username__in=previus)
    return thisOperator[0]


class ClientsView(CreateView):
    model = Clients
    form_class = ClientsForm
    template_name = 'clients/form.html'
    success_url = '/thanks/' #reverse_lazy('/')

    def form_valid(self, form):
            cd = form.cleaned_data
            # subject = 'Новая заявка от {} - сумму удержания {} '.format(cd['name'], cd['summ'], )
            message = '{}. На сумму {} Планирует заказать пакет {} Телефон:{}. Коротко про {}'.format(cd['name'], cd['summ'], cd['price'], cd['tel'], cd['about'])
            # html_message = '{} из {}.<br /> Имеет {} на сумму {}<br /> Планирует заказать пакет {}<br /> Телефон:{}<br/><hr/>{}'.format(
            #     cd['name'], cd['region'], cd['penalty'], cd['summ'], cd['price'], cd['tel'], cd['about'])
            # send_mail(subject, message, 'send@fotka.kiev.ua', ['v.shestakov@dgfinance.com.ua'], html_message=html_message)
            # send_mail(subject, message, 'send@fotka.kiev.ua', ['e.kiyanitsa@dgfinance.com.ua'], html_message=html_message)
            # send_mail(subject, message, 'send@fotka.kiev.ua', ['soxwhite@gmail.com'], html_message=html_message)
            # TODO uncoment send messages
            new_clients(message)

            form.instance.pathFrom = 'site'
            form.instance.operator =operator_sort()

            return super(ClientsView, self).form_valid(form)

anticollect_org/apps/index/views.py
from django.shortcuts import render
from .models import Price, Contacts, Banner, InfoOne, Services, InfoTwo, Stages, Guarantees, Feedbacks


def index(request):
    try:
        banner = Banner.objects.get(status='published')
    except:
        banner = ''
    infoone = InfoOne.objects.filter(status='published')
    services = Services.objects.filter(status='published')
    infotwo = InfoTwo.objects.filter(status='published')

    stages = Stages.objects.filter(status='published')
    price = Price.objects.filter(status='published')
    guarantees = Guarantees.objects.filter(status='published')
    feedbacks = Feedbacks.objects.filter(status='published')


    return render(request, 'index/idx.html', {
        'banner': banner,
        'infoone': infoone,
        'services': services,
        'infotwo': infotwo,
        'stages': stages,
        'price': price,
        'guarantees': guarantees,
        'feedbacks': feedbacks,
    })

anticollect_org/templates/clients/-clients_form.html
{% load static %}
{#{% load photo_tags %}#}
{% load i18n %}
{#{% block head %}#}
{#<link href="{% static "css/form.css" %}" rel="stylesheet">#}
{#{% endblock %}#}

{#<div class="form_bgr">#}
<div class="container-fluid bg-info py-5" id="form-zakaz">
    <div class="row d-flex justify-content-center">
        <div class="col-7">
        <form action="{% url 'clients:clients' %}" method="post" class="d-flex flex-column">
            <h3 class="text-light text-center">{% translate 'Відправити запит' %}</h3>
            {% csrf_token %}
{#            {{ clients_form }}#}

            <div class="d-flex p-2 m-1">{{ clients_form.name }}</div>
            <div class="d-flex p-2 m-1">{{ clients_form.tel }}{{ clients_form.summ }}</div>
            <div class="d-flex p-2 m-1">{{ clients_form.region }}</div>
            <div class="d-flex p-2 m-1">{{ clients_form.penalty }}{{ clients_form.price }}</div>
            <div class="d-flex p-2 m-1">{{ clients_form.about }}</div>
            <button class="btn_form"><span class="btn_form_text">{% translate 'Отправить заявку' %}</span></button>
        </form>
        </div>
    </div>
</div>
{#</div>#}
{## 'name', 'tel', 'summ', 'region', 'penalty', 'price', 'about'#}

anticollect_org/templates/clients/form.html
{% load static %}
{#{% load index_tags %}#}
{% load i18n %}
{% block head %}

{#<link href="{% static "css/form.css" %}" rel="stylesheet">#}
{#    <script>#}
{#    $(".btn_form").on("click", function() {#}
{#    $.post("http://some/endpoint/here", $("#my-form").serialize())#}
{#        .done(function() { window.alert("Successfully submitted!"); })#}
{#        .fail(function() { window.alert("Submission failed!"); });#}
{#    });#}
{#    </script>#}

{% endblock %}

<div class="container-fluid bg-info py-5" id="contactForm">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
        <form action="{% url 'clients:clients' %}" method="post" class="d-flex flex-column">
            <h3 class="text-light text-center">{% translate "Відправити запит" %}</h3>
            {% csrf_token %}
            <div class="d-flex m-1">{{ clients_form.name }}</div>
            <div class="d-flex m-1">{{ clients_form.tel }} &nbsp {{ clients_form.summ }}</div>
            <div class="d-flex m-1">{{ clients_form.price }}</div>
            <div class="d-flex m-1">{{ clients_form.about }}</div>
            <div class="d-flex m-1 justify-content-end"><button class="btn btn-outline-light"><span class="btn_form_text">{% translate 'Відправити запит' %}</span></button></div>
        </form>
        </div>
    </div>
</div>



{#</div>#}
{## 'name', 'tel', 'summ', 'region', 'penalty', 'price', 'about'#}

anticollect_org/templates/clients/small-form.html
{% load static %}
{% load index_tags %}
{% load i18n %}




<!-- Modal -->
<div id="exampleModal" class="modal fade" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form action="{% url 'clients:clients' %}" method="post" class="d-flex flex-column">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 id="exampleModalLabel" class="modal-title">{% translate 'Відправити запит' %}</h5>
                    <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="d-flex m-1">{{ clients_form.tel }} </div>
                    {#            <div class="d-flex m-1 justify-content-end">#}
                    {#                <button class="btn btn-outline-light">#}
                    {#                    <span class="btn_form_text">{% translate 'Отправить заявку' %}</span>#}
                    {#                </button>#}
                    {#            </div>#}
                </div>
                <div class="modal-footer">
{#                    <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Close</button>#}
                    <button class="btn btn-primary">{% translate 'Відправити запит' %}</button>
                </div>
            </div>
        </form>
    </div>
</div>





{#</div>#}
{## 'name', 'tel', 'summ', 'region', 'penalty', 'price', 'about'#}