anticollect_org/apps/blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='BlogList'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='BlogDetail')
]

anticollect_org/apps/bot/urls.py
from django.urls import path
from .tbb import sbot


urlpatterns = [
    path('D@NetQ3kNMh&4c-eRNw=_wVkfqM$j^Cd+b+BP9uyHsNG-Gaj*8+NBL_3qyEkzFWT/', sbot, name="bot"),
]

anticollect_org/apps/index/urls.py
from django.urls import path
# from . import views
from .views import index# BlocksListView

app_name = 'index'

urlpatterns = [
    # path('', BlocksListView.as_view(), name='index_page'),
    path('', index, name='index_page'),
]

anticollect_org/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('botTelegram/', include('bot.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('index.urls'), name='main'),
    path('blog/', include('blog.urls'), name='blog'),
    path('clients/', include('clients.urls')),
    path('thanks/', TemplateView.as_view(template_name='thanks.html'), name='thanks')
)

anticollect_org/apps/blog/models.py
from django.db import models
from tinymce.models import HTMLField
from django.urls import reverse
from io import BytesIO
from PIL import Image
from django.core.files import File
from django.utils.safestring import  mark_safe


#take name from path
def ImgName(img):
    arr = img.split('/')
    return arr[-1]

#image compression method
def compress(image):

    im = Image.open(image)
    # imR = im.resize(1600)
    # im_io = BytesIO()
    NewImageName = ImgName(image.name)
    # im_io.name = NewImageName
    im.save(NewImageName, 'JPEG', quality=60, )
    new_image = File(NewImageName, name=NewImageName)
    print('newImage', NewImageName)
    return new_image

def dublicateDelite(image):
    arr = image.split('/')
    arr2 = []
    for a in arr:
        if (arr2.count(a) == 0):
            arr2.append(a)
    newUrls = '/'.join(arr2)
    return newUrls

def newPath(imgPath, image):
    containPath = image.find(imgPath)
    if (containPath >0):
        return dublicateDelite(image)
    else:
        return imgPath + image

# def bannerImg(obj, image):
#     # imgPath = 'photo/' + str(obj.slug) + '/banner.jpeg'
#     # nPath = dublicateDelite(image)
#     return 'photo/' + str(obj.slug) + '/banner.jpeg'

def bannerImg(obj, image):
    imgPath = 'photo/' + str(obj.slug) + '/'
    # dublicateDelite(image)
    return newPath(imgPath, image)

class Blog(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Отключено'),
        ('published', 'Включено'),
    )
    blockName = models.CharField('Краткий Заголовок', max_length=60, help_text='Завликающий краткий заголовок')
    LongBlockName = models.CharField('Полный Заголовок статьи', max_length=150, blank=True, null=True, help_text='Полный заголовок описывающий всю суть')
    slug = models.SlugField('название для url', blank=True, null=True, help_text='название для ссылки, должно быть из латинских букв и цифр')
    created = models.DateTimeField(auto_now_add=True)
    lastmod = models.DateTimeField(auto_now=True)
    idsort = models.PositiveSmallIntegerField(verbose_name='Порядок сортировки', default=1, blank=True, null=True)
    banner = models.ImageField('Баннер для статьи', upload_to=bannerImg, blank=True, null=True, max_length=500,
                               help_text='Добавить привлекательную картинку для статьи')
    text = HTMLField('Наполнение блока', blank=True, max_length=20000)
    status = models.CharField('Состояние', max_length=20, choices=STATUS_CHOICES, null=True, blank=True, default='draft')
    metaDescrioption = models.CharField('SEO описание', max_length=155, null=True, blank=True,
                                        help_text='Описание страницы для поисковиков\n будет видно в снипете(выдача поиска в Google)')
    metaKeyWords = models.CharField('SEO Ключевые слова', max_length=155, null=True, blank=True,
                                    help_text='ключевые слова с поисковиков по теме')

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="150" />' % (self.banner))
    image_tag.short_description = 'Баннер'

    def get_absolute_url(self):
        return reverse('blog:BlogDetail', kwargs={'slug': self.slug, })

    # def save(self, *args, **kwargs):
    #     try:
    #         new_image = compress(self.banner)
    #         # new_image = newPath(imgPath ,compressedImg)
    #         self.banner = new_image
    #     except ValueError:
    #         pass
    #     super().save(*args, **kwargs)

    class Meta:
        ordering = ['id']
        verbose_name = 'Статьи'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.blockName

anticollect_org/apps/clients/models.py
from django.db import models
from django.utils.translation import gettext as _
from index.models import Price
from django.contrib.auth.models import User

class Penalty(models.Model):
    penalty = models.CharField('Завание удержания', max_length=50, null=True, blank=True)
    idsort = models.PositiveSmallIntegerField(verbose_name='Порядок сортировки', default=1)

    class Meta:
        ordering = ['idsort']
        verbose_name = 'Взыскания'
        verbose_name_plural = 'Типы взысканий'

    def __str__(self):
        return self.penalty

class Region(models.Model):
    region = models.CharField('Регион', max_length=50, null=True, blank=True)
    idsort = models.PositiveSmallIntegerField(verbose_name='Порядок сортировки', default=1)

    class Meta:
        ordering = ['idsort']
        verbose_name = 'Регион'
        verbose_name_plural = 'Регионы'

    def __str__(self):
        return self.region

CHOISES_FROM= (
        ('site', 'Сайт'),
        ('viber', 'Viber'),
    )


def cur_user(request):
    loginNow = request.user
    return loginNow


class Clients(models.Model):
    CHOISES_PROCES=(
        ('no_worked', 'Новый Клиент'),
        ('payed', 'Оплачено'),
        ('in_court', 'Подано в Суд'),
        ('to_back', 'Возврат'),
    )
    CHOISES_ZAYAVKA=(
        ('new', 'Новая заявка'),
        ('later', 'Перзвонить Позже'),
        ('dogovor', 'Аванс'),
        ('refusal', 'Отказ'),
    )
    name = models.CharField(_('ПІБ'), max_length=300, null=True, blank=True)
    # tel = PhoneField(help_text='Контактний телефон', E164_only=False)
    tel = models.CharField('Телефон', max_length=20, help_text='Контактний телефон')
    summ = models.FloatField('Стягнута сума, грн *', null=True, blank=True)
    region = models.ForeignKey(Region, verbose_name='Регион', on_delete=models.CASCADE, null=True, blank=True, default='')
    penalty = models.ForeignKey(Penalty, verbose_name='Взыскание',  on_delete=models.CASCADE, null=True, blank=True, default='')
    price = models.ForeignKey(Price, verbose_name='Тариф', on_delete=models.CASCADE, null=True, blank=True, default='')
    about = models.TextField('Описание', null=True, blank=True)
    dateAdd = models.DateTimeField('Дата создания', auto_now_add=True, help_text='Клиент создан', null=True, blank=True)
    lastModificate = models.DateTimeField('Последняя модификация', auto_now=True, help_text='последнее редактирование', null=True)
    processed = models.CharField('Статус клиента', choices=CHOISES_PROCES, max_length=20, blank=True, null=True, default='no_worked')
    pathFrom = models.CharField('Источник', choices=CHOISES_FROM, max_length=10, default='viber')
    datePayment = models.DateField('Дата по дог.', null=True, blank=True, auto_now=False)
    Payment = models.PositiveSmallIntegerField('Cумма по дог.', null=True, blank=True)
    operator = models.ForeignKey(User, verbose_name='Оператор', limit_choices_to={'groups__name': 'Operators'},
                                  null=True, blank=True, on_delete=models.SET_NULL)
    comments = models.TextField('Комментарии юриста', null=True, blank=True)
    manager = models.CharField('Статус заявки', choices=CHOISES_ZAYAVKA, max_length=15, blank=True, null=True, default='new')
    PrePayment = models.PositiveSmallIntegerField('Предоплата', null=True, blank=True)
    manager_comment = models.TextField('Комментарии менеджера', null=True, blank=True)



    class Meta:
        verbose_name = 'Заявка от клиента'
        verbose_name_plural = 'Заявки от клиентов'

    def __str__(self):
        return f'{self.tel}'

anticollect_org/apps/clients/forms.py
from django.core import validators
from django.core.validators import validate_email
from django import forms
from django.utils.translation import gettext_lazy as _
from clients.models import Clients, CHOISES_FROM
from index.models import Price


class ClientsForm(forms.ModelForm):
    price = forms.ModelChoiceField(queryset=Price.objects.all(),
                                   label='', required=False,
                                   empty_label=_("Виберіть послугу"),
                                   widget=forms.Select(attrs={'class': 'form-control'}),
                                   )
    pathFrom = 'site'
    operator = None
    class Meta:
        model = Clients
        fields = ('name', 'tel', 'summ', 'price', 'about', )
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': _('ПІБ'), 'class': 'form-control'}),
            'tel': forms.TextInput(attrs={'placeholder': _('Телефон'), 'class': 'form-control'}),
            'summ': forms.NumberInput(attrs={'placeholder': _('Стягнута сума, грн *'), 'class': 'form-control'}),
            'region': forms.Select(attrs={'class': 'form-control'}),
            'penalty': forms.Select(attrs={'class': 'form-control'}),
            'about': forms.Textarea(attrs={'placeholder': _('Короткий опис ситуації'), 'class': 'form-control'}),
            # 'pathFrom': forms.Textarea(),
        }
        labels = {
            'name': '',
            'email': '',
            'tel': '',
            'comments': '',
            # 'region':_('выберет регион'),
        }
        # default_validators = [
        #     validators.validate_email
        # ]

anticollect_org/apps/blog/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Blog
from index.models import Contacts

class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'
    slug_field = 'slug'
    ordering = 'idsort'
    context_object_name = 'blog_all'
    paginate_by = 12
    queryset = Blog.objects.filter(status='published').order_by('idsort')

    # def get_context_data(self, **kwargs):
    #     context = super(BlogListView, self).get_context_data(**kwargs)
    #     # context['index_all'] = Blocks.objects.filter(status='published').order_by('idsort')
    #     # context['contacts'] = Contacts.objects.get(id=1)
    #     return context

class BlogDetailView(DetailView):
    model = Blog
    context_object_name = 'blog_one'
    # def get_context_data(self, **kwargs):
    #     context = super(BlogDetailView, self).get_context_data(**kwargs)
    #     context['index_all'] = Blocks.objects.filter(status='published').order_by('idsort')
    #     context['contacts'] = Contacts.objects.get(id=1)
    #     return context

anticollect_org/apps/clients/views.py
from django.views.generic import CreateView
from .models import Clients
from bot.tbb import new_clients
from .forms import ClientsForm
from django.contrib.auth.models import User


#from django.core.mail import send_mail


def operator_sort():
    previus = []
    cols = User.objects.filter(groups__name='Operators').count()
    serched = cols - 1
    for i in range(serched):
        previus.append(str(Clients.objects.filter(pathFrom='site').order_by('-dateAdd')[i].operator))
    thisOperator = User.objects.filter(groups__name='Operators').exclude(username__in=previus)
    return thisOperator[0]


class ClientsView(CreateView):
    model = Clients
    form_class = ClientsForm
    template_name = 'clients/form.html'
    success_url = '/thanks/' #reverse_lazy('/')

    def form_valid(self, form):
            cd = form.cleaned_data
            # subject = 'Новая заявка от {} - сумму удержания {} '.format(cd['name'], cd['summ'], )
            message = '{}. На сумму {} Планирует заказать пакет {} Телефон:{}. Коротко про {}'.format(cd['name'], cd['summ'], cd['price'], cd['tel'], cd['about'])
            # html_message = '{} из {}.<br /> Имеет {} на сумму {}<br /> Планирует заказать пакет {}<br /> Телефон:{}<br/><hr/>{}'.format(
            #     cd['name'], cd['region'], cd['penalty'], cd['summ'], cd['price'], cd['tel'], cd['about'])
            # send_mail(subject, message, 'send@fotka.kiev.ua', ['v.shestakov@dgfinance.com.ua'], html_message=html_message)
            # send_mail(subject, message, 'send@fotka.kiev.ua', ['e.kiyanitsa@dgfinance.com.ua'], html_message=html_message)
            # send_mail(subject, message, 'send@fotka.kiev.ua', ['soxwhite@gmail.com'], html_message=html_message)
            # TODO uncoment send messages
            new_clients(message)

            form.instance.pathFrom = 'site'
            form.instance.operator =operator_sort()

            return super(ClientsView, self).form_valid(form)

anticollect_org/apps/index/views.py
from django.shortcuts import render
from .models import Price, Contacts, Banner, InfoOne, Services, InfoTwo, Stages, Guarantees, Feedbacks


def index(request):
    try:
        banner = Banner.objects.get(status='published')
    except:
        banner = ''
    infoone = InfoOne.objects.filter(status='published')
    services = Services.objects.filter(status='published')
    infotwo = InfoTwo.objects.filter(status='published')

    stages = Stages.objects.filter(status='published')
    price = Price.objects.filter(status='published')
    guarantees = Guarantees.objects.filter(status='published')
    feedbacks = Feedbacks.objects.filter(status='published')


    return render(request, 'index/idx.html', {
        'banner': banner,
        'infoone': infoone,
        'services': services,
        'infotwo': infotwo,
        'stages': stages,
        'price': price,
        'guarantees': guarantees,
        'feedbacks': feedbacks,
    })

anticollect_org/templates/base.html
{% load static %}
{% load index_tags %}
{% load clients_tags %}
{% load i18n %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% if meta %}{% block metaDescription %}{% endblock %}{% else %}{% translate 'ТОВ Невідкладна правова допомога, повернення незаконно стягнутих коштів та компенсація понесених витрат за виконавчим написом нотаріуса.' %}{% endif %}">
    <meta name="keywords" content="{% if meta %}{% block metaKeywords %}{% endblock %}{% else %}{% translate 'снять арест, зняття арешту, виконавчий напис нотаріус, исполнительная надпись нотариус' %}{% endif %}">
    <title>{% if title %}{% block title %}{% endblock %}{% else %}{% translate 'Оскарження виконавчого напису нотаріуса' %}{% endif %}</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    <link href="{% static "css/index.css" %}" rel="stylesheet">
    <script async="" src="{% static "js/index.js" %}"></script>
{#    <script src="https://unpkg.com/jquery-input-mask-phone-number@1.0.14/dist/jquery-input-mask-phone-number.js"></script>#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.1.62/jquery.inputmask.bundle.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans+SC:wght@100&display=swap" rel="stylesheet">

    <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-9XM7PJ5P5F"></script>
    <script>
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-9XM7PJ5P5F', {
                page_path: window.location.pathname,
            });
    </script>
<script>

</script>

    {% block head %}{% endblock %}
</head>
<body>
{% include "menu.html" %}
{#{% navigation %}#}


{#<a class="btn btn-outline-primary align-self-stretch m-1" href="{% url 'blog:BlogList' %}">{% translate 'Статті' %}</a>#}
            </div>
            <div class="col text-light justify-content-end">
                <div class="d-flex">
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        {% if language.code != LANGUAGE_CODE %}
                            <a href="/{{ language.code }}{{ curentPath }}{{ request.get_full_path|slice:'3:' }}" class="selected" lang="{{ language.code }}">
{#                                <img src="{% static "lang/" %}{{ language.code }}.gif">#} {% translate 'Рус' %}
                            </a> &nbsp;
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </nav>
</div>
{% small_form %}

<div style="height:70px; width: 100px;"> &nbsp;</div>
<div class="d-flex flex-column min-vh-100 ">
    <div class="flex-1 overflow-hidden">
        {% block content %}{% endblock %}
    </div>
    <div class="mt-auto">

        {% footer %}

    </div>
</div>
</body>
</html>

anticollect_org/templates/d-menu.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% for obj in navigation %}
    {% if obj.name %}
        <a class="btn btn-outline-primary align-self-stretch  m-1 mx-3" href="
{% if 'http' in obj.link or 'www' in obj.link %}{% else %}/{{ LANGUAGE_CODE }}{% endif %}{{ obj.link }}
">{{ obj.name }}</a>
    {% endif %}
{% endfor %}

anticollect_org/templates/footer.html
<div class="container-fluid bg-secondary text-light text-center py-2"  style="color: #252525;">
    <div  style="color: #252525;">{% if contacts.name %}{{ contacts.name }}{% endif %}</div>
    <div  style="color: #252525;">{% if contacts.adress %}{{ contacts.adress }}{% endif %} {% if contacts.code %}, Код ЄДРПОУ: {{ contacts.code }}{% endif %} </div>

    {% if contacts.tel %}<div  style="color: #252525;">Телефон: <a  style="color: #252525;" href="tel:+{{ contacts.tel }}" title="+{{ contacts.tel }}">+{{ contacts.tel }}</a>,{% endif %}
    {% if contacts.email %}{{ contacts.email }}{% endif %}</div>
</div>

anticollect_org/templates/thanks.html
{% extends "base.html" %}
{% load clients_tags %}
{% load i18n %}
{% block title %}

{% endblock %}
{% block head %}

{% endblock %}

{% block content %}
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
    <h1>{% translate 'Дякуємо за звернення' %}!</h1>
    <p>{% translate "Наш спеціаліст зв'яжеться з вами найближчим часом" %}.</p>
    </div>
{% endblock %}